# timeout
timeout = "1200s"
baseURL = 'https://svenschnieders.com/1437studio/'
# your website url
# website title
title = '1437 studio'
# don't touch this
disableKinds = ["section", "taxonomy", "term", "home"]
# robots.txt
enableRobotsTXT = true
# available options
# * en (powered by Geist)
# * de (powered by Geist)
# * es (powered by Geist)
# * fr (powered by Geist)
# * it (powered by Geist)
# * zh-sg zh-cn (powered by Noto Sans SC)
# * zh-hk zh-tw zh-mo (powered by Noto Sans TC)
# * ja (powered by Noto Sans JP)
# * ko (powered by Noto Sans KR)
defaultContentLanguage = 'en'

# theme as module
[module]
[[module.imports]]
path = "bridget" # deploy with git (recommended)  WARN: you should also set `bundled` to true in params.toml !!!
